url: "https://azurasghost.xyz" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/azurasGhost" # the subpath of your site, e.g. /blog
title: "azurasGhost" # the name of your site, e.g. ACME Corp.
